# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "modal>=1.0",
#     "pandas",
# ]
# ///
"""PRODIGY binding-affinity scoring on RBX1 complex structures.

PRODIGY (https://github.com/haddocking/prodigy) is a contact-based
predictor of binding free energy / dissociation constant. We run it on
every pre-computed (target=RBX1, binder) complex generated by the four
structure predictors used for this paper:

* ``boltz2``    — ``data/structures/boltz2/{pb_id}.cif``
* ``chai``      — ``data/structures/chai/{pb_id}.cif``
* ``protenix``  — ``data/structures/protenix/{pb_id}.cif``
* ``af2m``      — ``data/structures/af2m/{pb_id}.pdb``

On the Modal volume the same paths are persisted by the sibling Modal
apps (``modal_{boltz2,chai1,protenix}_rbx1.py``). PRODIGY traditionally
ingests PDB; newer versions of ``prodigy-prot`` accept mmCIF directly,
but to stay robust we convert CIF → PDB via Biopython before invoking
the CLI.

Outputs (Modal Volume ``rbx1-rerun-results``):

* ``prodigy/{pb_id}.json`` — one record per pb_id, with one sub-dict per
  source predictor::

      {
        "pb_id": "amber-bat-maple",
        "boltz2":   {"status": "ok", "dG": -10.2, "kd": 3.5e-8, "pkd": 7.46},
        "chai":     {"status": "ok", "dG":  -9.7, "kd": 7.9e-8, "pkd": 7.10},
        "protenix": {"status": "ok", "dG":  -8.3, "kd": 9.1e-7, "pkd": 6.04},
        "af2m":     {"status": "ok", "dG": -11.1, "kd": 7.2e-9, "pkd": 8.14}
      }

  Predictors with no structure on the volume are omitted from the dict.

Usage::

    cd <repo_root>
    modal run --detach scripts/modal/modal_prodigy_rbx1.py
    modal run scripts/modal/modal_prodigy_rbx1.py --download

    CONCURRENCY=50 modal run --detach scripts/modal/modal_prodigy_rbx1.py
"""

from __future__ import annotations

import contextlib
import json
import os
import re
from pathlib import Path

import modal

CONCURRENCY = int(os.environ.get("CONCURRENCY", 30))
TIMEOUT_MIN = int(os.environ.get("TIMEOUT", 30))

# Modal app / volume names — overridable for external users.
APP_NAME = os.environ.get("MODAL_APP_NAME", "rbx1-prodigy")
RESULTS_VOLUME_NAME = os.environ.get("MODAL_RESULTS_VOLUME", "rbx1-rerun-results")

# Source predictors, in the order their results are recorded.
SOURCE_PREDICTORS: tuple[str, ...] = ("boltz2", "chai", "protenix", "af2m")
PREDICTOR = "prodigy"  # destination folder on the volume

# ---------------------------------------------------------------------------
# Modal image — PRODIGY only (no FoldX)
# ---------------------------------------------------------------------------

prodigy_image = (
    modal.Image.debian_slim(python_version="3.11")
    .pip_install("biopython>=1.80", "prodigy-prot>=1.0", "numpy")
)

orchestrator_image = modal.Image.debian_slim(python_version="3.11").pip_install("pandas")

app = modal.App(APP_NAME)

RESULTS_VOLUME = modal.Volume.from_name(RESULTS_VOLUME_NAME, create_if_missing=True)
RESULTS_DIR = f"/{RESULTS_VOLUME_NAME}"


# ---------------------------------------------------------------------------
# Per-source PRODIGY scoring helper (runs inside the remote container)
# ---------------------------------------------------------------------------


def _score_one_source(struct_path: Path) -> dict:
    """Run PRODIGY on a single CIF/PDB. Returns a sub-dict ready for JSON output.

    Keys: ``status``, ``dG`` (kcal/mol), ``kd`` (M), ``pkd``. On failure,
    ``status`` is an error string and the numeric fields are ``None``.
    """
    import subprocess
    import tempfile

    import numpy as np

    pdb_for_prodigy = str(struct_path)
    cleanup: Path | None = None

    if struct_path.suffix.lower() in (".cif", ".mmcif"):
        # PRODIGY's bundled freesasa parser is PDB-only; convert via Biopython.
        try:
            from Bio.PDB import MMCIFParser, PDBIO

            parser = MMCIFParser(QUIET=True)
            structure = parser.get_structure("s", str(struct_path))
            tmp = Path(tempfile.mkdtemp()) / (struct_path.stem + ".pdb")
            io = PDBIO()
            io.set_structure(structure)
            io.save(str(tmp))
            pdb_for_prodigy = str(tmp)
            cleanup = tmp
        except Exception as e:
            return {"status": f"error: cif->pdb conversion failed: {e}", "dG": None, "kd": None, "pkd": None}

    try:
        proc = subprocess.run(
            ["prodigy", pdb_for_prodigy, "--selection", "A", "B"],
            capture_output=True,
            text=True,
            timeout=120,
        )
        output = (proc.stdout or "") + (proc.stderr or "")

        kd_match = re.search(
            r"dissociation constant \(M\) at\s*[0-9.]+[^\n]*C:\s*([0-9.eE+-]+)",
            output,
        )
        if not kd_match:
            kd_match = re.search(r"Kd\s*=\s*([0-9.eE+-]+)", output)
        dg_match = re.search(r"binding (?:free )?energy.*?(-?[0-9.]+)\s*kcal", output)

        if not kd_match and not dg_match:
            return {
                "status": f"error: parse failed: {output[:200]}",
                "dG": None,
                "kd": None,
                "pkd": None,
            }

        kd = float(kd_match.group(1)) if kd_match else None
        pkd = float(-np.log10(kd)) if (kd is not None and kd > 0) else None
        dg = float(dg_match.group(1)) if dg_match else None

        return {"status": "ok", "dG": dg, "kd": kd, "pkd": pkd}

    except Exception as e:
        return {"status": f"error: {e}", "dG": None, "kd": None, "pkd": None}
    finally:
        if cleanup is not None:
            with contextlib.suppress(Exception):
                cleanup.unlink(missing_ok=True)
                cleanup.parent.rmdir()


# ---------------------------------------------------------------------------
# Remote function: score one pb_id across all available source predictors
# ---------------------------------------------------------------------------


@app.function(
    image=prodigy_image,
    volumes={RESULTS_DIR: RESULTS_VOLUME},
    timeout=TIMEOUT_MIN * 60,
    retries=1,
    max_containers=CONCURRENCY,
)
def score_prodigy(pb_id: str) -> dict:
    """Run PRODIGY on every available {boltz2, chai, protenix, af2m} structure
    for a single pb_id and persist the merged JSON to the volume.
    """
    RESULTS_VOLUME.reload()

    out_path = Path(RESULTS_DIR) / PREDICTOR / f"{pb_id}.json"
    # First scan which source structures actually exist on the volume so we
    # don't skip a rerun just because the JSON was written before AF2-M /
    # Protenix landed.
    available_sources: set[str] = set()
    for src in SOURCE_PREDICTORS:
        struct_dir = Path(RESULTS_DIR) / "structures" / src
        if (struct_dir / f"{pb_id}.cif").exists() or (struct_dir / f"{pb_id}.pdb").exists():
            available_sources.add(src)

    if out_path.exists():
        try:
            cached = json.loads(out_path.read_text())
            cached_sources = {k for k in cached if k in SOURCE_PREDICTORS}
            # Skip only if every available source is already scored ok.
            if available_sources and available_sources.issubset(cached_sources) and all(
                isinstance(cached.get(s), dict) and cached[s].get("status") == "ok"
                for s in available_sources
            ):
                return cached
        except Exception:
            cached = {}
    else:
        cached = {}

    result: dict = {"pb_id": pb_id}

    for src in SOURCE_PREDICTORS:
        struct_dir = Path(RESULTS_DIR) / "structures" / src
        # boltz2/chai/protenix write .cif, af2m writes .pdb. Look for both
        # so we degrade gracefully if a future rerun changes the format.
        candidates = [struct_dir / f"{pb_id}.cif", struct_dir / f"{pb_id}.pdb"]
        struct_file = next((p for p in candidates if p.exists()), None)
        if struct_file is None:
            # No structure for this source — omit from the output.
            continue

        sub = _score_one_source(struct_file)
        sub["source_path"] = str(struct_file.relative_to(RESULTS_DIR))
        result[src] = sub

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(result))
    RESULTS_VOLUME.commit()

    return result


# ---------------------------------------------------------------------------
# Remote orchestrator
# ---------------------------------------------------------------------------


@app.function(
    image=orchestrator_image,
    timeout=12 * 3600,
    volumes={RESULTS_DIR: RESULTS_VOLUME},
)
def run_batch(pb_ids: list[str]) -> None:
    """Fan out PRODIGY scoring across all pb_ids, then write a flat CSV summary."""
    import pandas as pd

    RESULTS_VOLUME.reload()
    pred_dir = Path(RESULTS_DIR) / PREDICTOR
    pred_dir.mkdir(parents=True, exist_ok=True)

    completed: set[str] = set()
    for f in pred_dir.glob("*.json"):
        with contextlib.suppress(Exception):
            d = json.loads(f.read_text())
            srcs = {k for k in d if k in SOURCE_PREDICTORS}
            if srcs and all(
                isinstance(d.get(s), dict) and d[s].get("status") == "ok" for s in srcs
            ):
                completed.add(d.get("pb_id") or f.stem)

    pending = [p for p in pb_ids if p not in completed]
    print(f"PRODIGY: {len(completed)} done, {len(pending)} pending (of {len(pb_ids)})")

    if pending:
        for done, result in enumerate(
            score_prodigy.map(pending, return_exceptions=True), start=1
        ):
            if isinstance(result, Exception):
                print(f"  exception: {result}")
            elif done % 25 == 0:
                print(f"  {done}/{len(pending)} done")

    # Flat CSV summary: one row per (pb_id, source).
    RESULTS_VOLUME.reload()
    rows: list[dict] = []
    for f in pred_dir.glob("*.json"):
        with contextlib.suppress(Exception):
            d = json.loads(f.read_text())
            pb_id = d.get("pb_id") or f.stem
            for src in SOURCE_PREDICTORS:
                sub = d.get(src)
                if not isinstance(sub, dict):
                    continue
                rows.append(
                    {
                        "pb_id": pb_id,
                        "source": src,
                        "status": sub.get("status"),
                        "prodigy_dG": sub.get("dG"),
                        "prodigy_kd": sub.get("kd"),
                        "prodigy_pkd": sub.get("pkd"),
                    }
                )

    df = pd.DataFrame(rows)
    csv_path = Path(RESULTS_DIR) / f"{PREDICTOR}_summary.csv"
    df.to_csv(csv_path, index=False)
    RESULTS_VOLUME.commit()
    ok = int((df["status"] == "ok").sum()) if "status" in df.columns else 0
    print(f"PRODIGY: {ok}/{len(df)} (pb_id, source) pairs succeeded.")


# ---------------------------------------------------------------------------
# Local entrypoint
# ---------------------------------------------------------------------------


@app.local_entrypoint()
def main(
    designs_csv: str = "./data/designs.csv",
    limit: int | None = None,
    download: bool = False,
    retry_failed: bool = False,
) -> None:
    """Trigger PRODIGY scoring on Modal, or pull results to local disk."""
    import pandas as pd

    if download:
        _download_to_local(designs_csv)
        return

    if retry_failed:
        _clear_failed()
        return

    df = pd.read_csv(designs_csv)
    if "pb_id" not in df.columns:
        raise RuntimeError(f"{designs_csv} is missing a 'pb_id' column")
    pb_ids = df["pb_id"].astype(str).tolist()
    if limit:
        pb_ids = pb_ids[:limit]

    print(f"Triggering PRODIGY batch: {len(pb_ids)} designs across {SOURCE_PREDICTORS}")
    run_batch.remote(pb_ids)
    print("Done. Pull results with `--download`.")


def _download_to_local(designs_csv: str) -> None:
    """Pull all per-pb_id PRODIGY JSONs into ``data/metrics/prodigy/``."""
    import pandas as pd

    df = pd.read_csv(designs_csv)
    expected_ids = set(df["pb_id"].astype(str).tolist())

    json_out = Path("./data/metrics") / PREDICTOR
    json_out.mkdir(parents=True, exist_ok=True)

    n_json = 0
    try:
        for entry in RESULTS_VOLUME.iterdir(PREDICTOR):
            if not entry.path.endswith(".json"):
                continue
            pb_id = Path(entry.path).stem
            if pb_id not in expected_ids:
                continue
            payload = b"".join(RESULTS_VOLUME.read_file(entry.path))
            (json_out / f"{pb_id}.json").write_bytes(payload)
            n_json += 1
    except Exception as e:
        print(f"  no PRODIGY JSONs to download: {e}")

    print(f"Downloaded {n_json} JSON for {PREDICTOR} -> {json_out}.")


def _clear_failed() -> None:
    """Remove per-pb_id JSONs whose recorded sources are all errors,
    so a re-run with ``modal run`` picks them up again."""
    cleared = 0
    try:
        for entry in RESULTS_VOLUME.iterdir(PREDICTOR):
            if not entry.path.endswith(".json"):
                continue
            try:
                data = json.loads(b"".join(RESULTS_VOLUME.read_file(entry.path)))
            except Exception:
                continue
            srcs = {k for k in data if k in SOURCE_PREDICTORS}
            if srcs and all(
                isinstance(data.get(s), dict)
                and str(data[s].get("status", "")).startswith("error")
                for s in srcs
            ):
                RESULTS_VOLUME.remove_file(entry.path)
                cleared += 1
    except Exception:
        pass
    print(f"  cleared {cleared} fully-failed results")
